bind r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "tmux-256color"
set -g prefix C-a
set -g mouse on
set -g base-index 1
set -g renumber-windows on
set -g escape-time 0
setw -g pane-base-index 1

# Stop tmux from renaming windows automatically
set-option -g automatic-rename-format "#{pane_current_command}"
set-option -g allow-rename on
set-window-option -g automatic-rename on

set -g set-clipboard on
set -g status-keys vi
set-window-option -g mode-keys vi

unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

bind-key -r n next-window
bind-key -r p previous-window

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
